export const CART_ACTION_TYPE = {
  SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
  SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
};

// export const CART_ACTION_TYPE = {
//   SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
//   ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
//   REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
//   CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
// };
